"""Offline pre-grasp joint waypoints for curriculum / reset bootstrap.

Generated by ``scripts/export_open_drawer_pregrasp.py`` (Method A: Isaac probe + DSR ikin).
"""

from __future__ import annotations

import math
import os
from typing import Any

import yaml

from tool_transfer_bot.assets.doosan_e0509 import RL_HOME_JOINT_DEG
from tool_transfer_bot.paths import PROJECT_ROOT

_DEFAULT_YAML = os.path.join(
    PROJECT_ROOT, "source", "tool_transfer_bot", "data", "open_drawer_pregrasp.yaml"
)


def _load_pregrasp_yaml(path: str | None = None) -> dict[str, Any]:
    yaml_path = path or os.environ.get("OPEN_DRAWER_PREGRASP_YAML", _DEFAULT_YAML)
    if not os.path.isfile(yaml_path):
        return {"joint_deg": dict(RL_HOME_JOINT_DEG), "meta": {"source": "fallback_home"}}
    with open(yaml_path, encoding="utf-8") as f:
        return yaml.safe_load(f)


_DATA = _load_pregrasp_yaml()

OPEN_DRAWER_PREGRASP_JOINT_DEG: dict[str, float] = _DATA.get("joint_deg", dict(RL_HOME_JOINT_DEG))
OPEN_DRAWER_PREGRASP_META: dict[str, Any] = _DATA.get("meta", {})

# Convenience rad dict for teleop / debug scripts.
OPEN_DRAWER_PREGRASP_JOINT_RAD: dict[str, float] = {
    name: (math.radians(deg) if name.startswith("joint_") else deg)
    for name, deg in OPEN_DRAWER_PREGRASP_JOINT_DEG.items()
}
